all:
	gcc main.c contacts.c -o contacts

test_1:
	gcc -DTEST_1=1 main.c contacts.c tests.c -o test_1

test_2:
	gcc -DTEST_2=1 main.c contacts.c tests.c -o test_2

test_3:
	gcc -DTEST_3=1 main.c contacts.c tests.c -o test_3

test_4:
	gcc -DTEST_4=1 main.c contacts.c tests.c -o test_4

clear_tests:
	rm -rf test_*
